site_name: phpSPA Documentation
site_description: Build Native PHP SPAs Without JavaScript Frameworks
site_author: Dave Conco
site_url: https://phpspa.readthedocs.io

# Repository (replace with your repo)
repo_name: dconco/phpspa
repo_url: https://github.com/dconco/phpspa
edit_uri: edit/main/docs/

# Theme configuration
theme:
   name: material
   palette:
      # Palette toggle for light mode
      - scheme: default
        primary: blue
        accent: blue
        toggle:
           icon: material/brightness-7
           name: Switch to dark mode
      # Palette toggle for dark mode
      - scheme: slate
        primary: blue
        accent: blue
        toggle:
           icon: material/brightness-5
           name: Switch to light mode
   features:
      - navigation.tabs
      - navigation.sections
      - navigation.top
      - search.highlight
      - search.share
      - content.code.annotate
      - content.code.copy
   custom_dir: docs/overrides/

# Markdown extensions
markdown_extensions:
   - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

   - pymdownx.highlight:
        anchor_linenums: true
   - pymdownx.inlinehilite
   - pymdownx.superfences:
        custom_fences:
           - name: mermaid
             class: mermaid
             format:
                !!python/name:pymdownx.superfences.fence_code_format # Other useful extensions


   - toc:
        permalink: true
   - admonition
   - pymdownx.details
   - pymdownx.tabbed:
        alternate_style: true
   - attr_list
   - tables

# Navigation structure
nav:
   - Home: index.md
   - Introduction: 1-introduction.md
   - Getting Started: 2-getting-started.md
   - Basics:
        - Creating Your First Component: 3-creating-your-first-component.md
        - Routing and Parameters: 4-routing-and-parameters.md
        - Route Patterns and Parameter Types: 5-route-patterns-and-param-types.md
   - Core Concepts:
        - Loading Events: 6-loading-events.md
        - Layout and Content Swap Mechanism: 7-layout-and-content-swap-mechanism.md
        - Component Rendering and Target Areas: 8-component-rendering-and-target-areas.md
        - Component Nesting: 10-component-nesting.md
        - Component Props: 11-component-props.md
   - Advanced Features:
        - Route Case Sensitivity: 12-route-case-sensitivity.md
        - Setting Page Titles: 13-setting-page-titles.md
        - Handling Error Routes: 14-handling-error-routes.md
        - JavaScript Navigation: 15-javascript-navigation.md
        - State Management: 17-state-management.md
   - Development:
        - Component Script and Styles: 18-component-script-and-styles.md
        - Handling Loading States: 19-handling-loading-states.md
        - Request Handling: 20-request-handling.md
   - Final Notes: final-notes.md
   - Integrations:
        - Introduction: ./integrations/index.md
        - 🟢 Laravel Integration: ./integrations/laravel-integration.md
        - 🔵 Symfony Integration: ./integrations/symfony-integration.md
        - 🟡 CodeIgniter Integration: ./integrations/codeigniter-integration.md
        - 🟠 Pure PHP Integration: ./integrations/pure-php-integration.md
   - Latest Version (v1.1.0):
        - Introduction: ./v1.1/index.md
        - File Import Utility: ./v1.1/1-file-import-utility.md
        - State Management - map(): ./v1.1/2-mapping-in-state-management.md
        - Using Component Functions via HTML Tags: ./v1.1/3-using-component-functions-by-html-tags.md
        - Component Basics: ./v1.1/4-component-basics.md
        - Link Component: ./v1.1/5-link-component.md
        - HTML Attribute Array to String Conversion: ./v1.1/6-html-attribute-array-to-string-conversion.md
        - Redirect Function: ./v1.1/7-redirect-function.md
        - Navigate Component: ./v1.1/8-navigate-component.md

# Plugins
plugins:
   - search

# Extra configuration
extra:
   social:
      - icon: fontawesome/brands/github
        link: https://github.com/dconco/phpspa
      - icon: fontawesome/brands/twitter
        link: https://x.com/dave_conco
      - icon: fontawesome/brands/discord
        link: https://discord.gg/FeVQs73C
   version:
      provider: mike

# Copyright
copyright: Copyright &copy; 2025 Dave Conco
