site_name: phpSPA Documentation
site_description: Component-Based PHP Library for Modern Web Applications
site_author: Dave Conco
site_url: https://phpspa.readthedocs.io

# Repository
repo_name: dconco/phpspa
repo_url: https://github.com/dconco/phpspa
edit_uri: edit/main/new-docs/

# Theme configuration with enhanced design
theme:
   name: material
   custom_dir: overrides/
   palette:
      # Light mode
      - scheme: default
        primary: blue
        accent: indigo
        toggle:
           icon: material/brightness-7
           name: Switch to dark mode
      # Dark mode  
      - scheme: slate
        primary: blue
        accent: indigo
        toggle:
           icon: material/brightness-5
           name: Switch to light mode
   features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.path
      - navigation.top
      - navigation.footer
      - navigation.indexes
      - search.highlight
      - search.share
      - search.suggest
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      - content.code.select
      - content.tooltips
      - content.tabs.link
      - toc.follow
      - toc.integrate
   font:
      text: Inter
      code: JetBrains Mono
   icon:
      logo: material/code-braces
      repo: fontawesome/brands/github
      edit: material/pencil
      view: material/eye

# Enhanced Markdown extensions
markdown_extensions:
   # Core extensions
   - abbr
   - admonition
   - attr_list
   - def_list
   - footnotes
   - md_in_html
   - tables
   - toc:
        permalink: true
        title: On this page
   
   # PyMdown extensions for enhanced functionality
   - pymdownx.arithmatex:
        generic: true
   - pymdownx.betterem:
        smart_enable: all
   - pymdownx.caret
   - pymdownx.details
   - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
   - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
        use_pygments: true
   - pymdownx.inlinehilite
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.superfences:
        custom_fences:
           - name: mermaid
             class: mermaid
             format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.tabbed:
        alternate_style: true
        combine_header_slug: true
   - pymdownx.tasklist:
        custom_checkbox: true
   - pymdownx.tilde
   - pymdownx.snippets
   - pymdownx.critic
   - pymdownx.magiclink:
        repo_url_shorthand: true
        user: dconco
        repo: phpspa

# Enhanced navigation structure
nav:
   - Home: index.md
   - 🎯 Getting Started:
        - Overview: getting-started/index.md
        - Quick Start: getting-started/quick-start.md
        - Installation: getting-started/installation.md
        - Your First Component: getting-started/first-component.md
        - Template Project: getting-started/template-project.md
   
   - 🧩 Components:
        - Component Basics: components/index.md
        - Creating Components: components/creating-components.md
        - Component Structure: components/component-structure.md
        - Component Props: components/component-props.md
        - Component Nesting: components/component-nesting.md
        - HTML Tag Components: components/html-tag-components.md
        - Class Components: components/class-components.md
        - Built-in Components: components/built-in-components.md
   
   - 🧭 Routing & Navigation:
        - Routing Basics: routing/index.md
        - Route Patterns: routing/route-patterns.md
        - Route Parameters: routing/route-parameters.md
        - HTTP Methods: routing/http-methods.md
        - Navigation: routing/navigation.md
        - Link Component: routing/link-component.md
        - Route Case Sensitivity: routing/case-sensitivity.md
        - Error Routes: routing/error-routes.md
   
   - 🧠 State Management:
        - State Overview: state/index.md
        - Creating State: state/creating-state.md
        - Updating State: state/updating-state.md
        - State Mapping: state/state-mapping.md
        - Loading States: state/loading-states.md
        - Component State: state/component-state.md
   
   - ⚡ Performance:
        - Performance Overview: performance/index.md
        - HTML Compression: performance/compression.md
        - Caching Strategies: performance/caching.md
        - Production Optimization: performance/production.md
   
   - 🔧 Advanced Features:
        - App Configuration: advanced/index.md
        - Method Chaining: advanced/method-chaining.md
        - JavaScript Integration: advanced/javascript-integration.md
        - PHP Function Calls: advanced/php-function-calls.md
        - CORS Configuration: advanced/cors.md
        - Component Scripts & Styles: advanced/scripts-styles.md
        - Page Titles: advanced/page-titles.md
        - Target Areas: advanced/target-areas.md
        - Auto-Reload: advanced/auto-reload.md
   
   - 🛡️ Security:
        - Security Overview: security/index.md
        - CSRF Protection: security/csrf-protection.md
        - Request Handling: security/request-handling.md
        - Input Validation: security/input-validation.md
        - Best Practices: security/best-practices.md
   
   - 🔌 Integrations:
        - Framework Integration: integrations/index.md
        - Laravel Integration: integrations/laravel.md
        - Symfony Integration: integrations/symfony.md
        - CodeIgniter Integration: integrations/codeigniter.md
        - Pure PHP Integration: integrations/pure-php.md
   
   - 🎭 Events & Hooks:
        - Event System: events/index.md
        - Loading Events: events/loading-events.md
        - Lifecycle Hooks: events/lifecycle-hooks.md
        - Custom Events: events/custom-events.md
   
   - 🧪 Testing & Development:
        - Development Setup: development/index.md
        - Testing Components: development/testing.md
        - Debugging: development/debugging.md
        - Development Tools: development/tools.md
   
   - 📚 Examples & Recipes:
        - Common Patterns: examples/index.md
        - Authentication Example: examples/authentication.md
        - Real-time Updates: examples/real-time.md
        - Form Handling: examples/forms.md
        - Dashboard Example: examples/dashboard.md
   
   - 📖 API Reference:
        - API Overview: api/index.md
        - App Class: api/app.md
        - Component Class: api/component.md
        - Helper Functions: api/helpers.md
        - JavaScript API: api/javascript.md
   
   - 🆕 Migration & Updates:
        - Migration Guide: migration/index.md
        - Version 1.1.5 Changes: migration/v1-1-5.md
        - Breaking Changes: migration/breaking-changes.md
        - Upgrade Guide: migration/upgrade-guide.md

# Enhanced plugins
plugins:
   - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
   - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
           remove_comments: true
   - git-revision-date-localized:
        enable_creation_date: true
        type: timeago
   - tags:
        tags_file: tags.md

# Extra configuration
extra:
   version:
      provider: mike
      default: latest
   social:
      - icon: fontawesome/brands/github
        link: https://github.com/dconco/phpspa
        name: GitHub Repository
      - icon: fontawesome/brands/twitter
        link: https://x.com/dave_conco
        name: Follow on Twitter
      - icon: fontawesome/brands/discord
        link: https://discord.gg/FeVQs73C
        name: Join Discord
      - icon: fontawesome/brands/youtube
        link: https://youtube.com/@daveconco
        name: YouTube Channel
      - icon: fontawesome/solid/envelope
        link: mailto:concodave@gmail.com
        name: Email Contact
   generator: false
   analytics:
      feedback:
         title: Was this page helpful?
         ratings:
            - icon: material/emoticon-happy-outline
              name: This page was helpful
              data: 1
              note: >-
                 Thanks for your feedback!
            - icon: material/emoticon-sad-outline
              name: This page could be improved
              data: 0
              note: >-
                 Thanks for your feedback! Help us improve this page by
                 <a href="https://github.com/dconco/phpspa/issues/new/?title=[Docs%20Feedback]%20{title}%20-%20{url}" target="_blank" rel="noopener">telling us what you need</a>.

# Custom CSS and JavaScript
extra_css:
   - assets/stylesheets/extra.css
   - assets/stylesheets/custom.css

extra_javascript:
   - assets/javascripts/extra.js
   - assets/javascripts/mathjax.js
   - https://polyfill.io/v3/polyfill.min.js?features=es6
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Copyright
copyright: >
   Copyright &copy; 2025 <a href="https://github.com/dconco" target="_blank" rel="noopener">Dave Conco</a> –
   <a href="#__consent">Change cookie settings</a>
