site_name: phpSPA - Component-Based PHP Library
site_description: Build fast, reactive web applications with PHP components like React
site_author: Dave Conco
site_url: https://phpspa.readthedocs.io

# Repository
repo_name: dconco/phpspa
repo_url: https://github.com/dconco/phpspa
edit_uri: edit/main/new-docs/

# Theme configuration
theme:
   name: material
   palette:
      # Light mode
      - scheme: default
        primary: blue
        accent: cyan
        toggle:
           icon: material/brightness-7
           name: Switch to dark mode
      # Dark mode
      - scheme: slate
        primary: blue
        accent: cyan
        toggle:
           icon: material/brightness-4
           name: Switch to light mode
   
   features:
      - navigation.tabs
      - navigation.sections
      - navigation.expand
      - navigation.path
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - content.code.annotate
      - content.code.copy
      - content.tabs.link
      - content.tooltips
      - header.autohide
      - toc.follow
      - toc.integrate
   
   icon:
      logo: material/react
      repo: fontawesome/brands/github
   
   custom_dir: overrides/

# Markdown extensions
markdown_extensions:
   # Code highlighting
   - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
   - pymdownx.inlinehilite
   - pymdownx.superfences:
        custom_fences:
           - name: mermaid
             class: mermaid
             format: !!python/name:pymdownx.superfences.fence_code_format
   
   # Content organization
   - admonition
   - pymdownx.details
   - pymdownx.tabbed:
        alternate_style: true
   - pymdownx.tasklist:
        custom_checkbox: true
   
   # Navigation & links
   - toc:
        permalink: true
        title: On this page
   - attr_list
   - md_in_html
   - tables
   - footnotes
   
   # Enhanced formatting
   - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.snippets
   - pymdownx.caret
   - pymdownx.tilde

# Navigation structure
nav:
   - Home: index.md
   - Why phpSPA?: why-phpspa.md
   - Getting Started:
        - Quick Start: quick-start.md
        - Installation: installation.md
        - Your First App: first-app.md
   
   - Core Concepts:
        - Components: concepts/components.md
        - Routing: concepts/routing.md
        - State Management: concepts/state.md
   
   - Security:
        - CSRF Protection: security/csrf.md
   
   - Performance:
        - Compression & Optimization: performance/compression.md
   
   - Advanced:
        - PHP-JavaScript Bridge: advanced/php-js-bridge.md

# Plugins
plugins:
   - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
   - minify:
        minify_html: true

# Extra configuration
extra:
   version:
      provider: mike
      default: latest
   
   social:
      - icon: fontawesome/brands/github
        link: https://github.com/dconco/phpspa
        name: GitHub Repository
      - icon: fontawesome/brands/twitter
        link: https://x.com/dave_conco
        name: Follow on X/Twitter
      - icon: fontawesome/brands/discord
        link: https://discord.gg/FeVQs73C
        name: Join Discord Community
      - icon: fontawesome/brands/youtube
        link: https://youtube.com/@daveconco
        name: YouTube Channel
   
   analytics:
      provider: google
      property: !ENV GOOGLE_ANALYTICS_KEY
   
   tags:
      PHP: php
      Components: components
      React-like: react
      SPA: spa
      Performance: performance
      Security: security

# Copyright
copyright: |
  Copyright &copy; 2025 <a href="https://github.com/dconco" target="_blank" rel="noopener">Dave Conco</a> - 
  Made with ❤️ for PHP developers

# Custom CSS
extra_css:
   - stylesheets/extra.css

# Custom JS  
extra_javascript:
   - javascripts/extra.js
